# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_argument_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 138)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(390, 138))
        Form.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.radioButton_default = QtWidgets.QRadioButton(Form)
        self.radioButton_default.setGeometry(QtCore.QRect(10, 60, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_default.setFont(font)
        self.radioButton_default.setChecked(True)
        self.radioButton_default.setObjectName("radioButton_default")
        self.radioButton_prompt = QtWidgets.QRadioButton(Form)
        self.radioButton_prompt.setGeometry(QtCore.QRect(10, 90, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_prompt.setFont(font)
        self.radioButton_prompt.setObjectName("radioButton_prompt")
        self.pushButton_ok = QtWidgets.QPushButton(Form)
        self.pushButton_ok.setGeometry(QtCore.QRect(290, 100, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setStyleSheet("background-color: rgb(97, 97, 97);")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, -20, 391, 81))
        self.label.setMinimumSize(QtCore.QSize(391, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Input Argument Option"))
        self.radioButton_default.setText(_translate("Form", "Use the default value(s) specified in atomic test"))
        self.radioButton_prompt.setText(_translate("Form", "Prompt to input value(s)"))
        self.pushButton_ok.setText(_translate("Form", "OK"))
        self.label.setText(_translate("Form", "Detects atomic test that requires input argument(s).\n"
"Please choose the method to obtain value(s) for input argument. "))
