# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Perimeter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SAHCMainWindow(object):
    def setupUi(self, SAHCMainWindow):
        SAHCMainWindow.setObjectName("SAHCMainWindow")
        SAHCMainWindow.resize(962, 736)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SAHCMainWindow.sizePolicy().hasHeightForWidth())
        SAHCMainWindow.setSizePolicy(sizePolicy)
        SAHCMainWindow.setMinimumSize(QtCore.QSize(0, 600))
        SAHCMainWindow.setMouseTracking(True)
        SAHCMainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        SAHCMainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        SAHCMainWindow.setIconSize(QtCore.QSize(48, 48))
        self.centralwidget = QtWidgets.QWidget(SAHCMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_Info = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Info.setMinimumSize(QtCore.QSize(0, 220))
        self.textBrowser_Info.setMaximumSize(QtCore.QSize(16777215, 220))
        self.textBrowser_Info.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.textBrowser_Info.setObjectName("textBrowser_Info")
        self.gridLayout.addWidget(self.textBrowser_Info, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(940, 61))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 61))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Stop.setGeometry(QtCore.QRect(840, 27, 93, 28))
        self.pushButton_Stop.setStyleSheet("background-color: rgb(97, 97, 97);")
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Start.setGeometry(QtCore.QRect(740, 27, 93, 28))
        self.pushButton_Start.setStyleSheet("background-color: rgb(97, 97, 97);")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.lineEdit_Path = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Path.setEnabled(True)
        self.lineEdit_Path.setGeometry(QtCore.QRect(103, 27, 441, 25))
        self.lineEdit_Path.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Path.setReadOnly(True)
        self.lineEdit_Path.setObjectName("lineEdit_Path")
        self.pushButton_Path = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Path.setGeometry(QtCore.QRect(553, 26, 111, 28))
        self.pushButton_Path.setStyleSheet("background-color: rgb(97, 97, 97);")
        self.pushButton_Path.setObjectName("pushButton_Path")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(8, 27, 91, 21))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.qTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.qTabWidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.qTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.qTabWidget.setDocumentMode(False)
        self.qTabWidget.setTabsClosable(False)
        self.qTabWidget.setMovable(False)
        self.qTabWidget.setTabBarAutoHide(False)
        self.qTabWidget.setObjectName("qTabWidget")
        self.tab_ExecutionStatus = QtWidgets.QWidget()
        self.tab_ExecutionStatus.setAutoFillBackground(False)
        self.tab_ExecutionStatus.setObjectName("tab_ExecutionStatus")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_ExecutionStatus)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser_ExecutionStatus = QtWidgets.QTextBrowser(self.tab_ExecutionStatus)
        self.textBrowser_ExecutionStatus.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_ExecutionStatus.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_ExecutionStatus.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_ExecutionStatus.setSearchPaths([])
        self.textBrowser_ExecutionStatus.setOpenExternalLinks(False)
        self.textBrowser_ExecutionStatus.setObjectName("textBrowser_ExecutionStatus")
        self.gridLayout_4.addWidget(self.textBrowser_ExecutionStatus, 0, 0, 1, 1)
        self.qTabWidget.addTab(self.tab_ExecutionStatus, "")
        self.tab_ExecutionDetails = QtWidgets.QWidget()
        self.tab_ExecutionDetails.setObjectName("tab_ExecutionDetails")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_ExecutionDetails)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser_ExecutionDetails = QtWidgets.QTextBrowser(self.tab_ExecutionDetails)
        self.textBrowser_ExecutionDetails.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_ExecutionDetails.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_ExecutionDetails.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_ExecutionDetails.setOpenExternalLinks(False)
        self.textBrowser_ExecutionDetails.setObjectName("textBrowser_ExecutionDetails")
        self.gridLayout_2.addWidget(self.textBrowser_ExecutionDetails, 0, 0, 1, 1)
        self.qTabWidget.addTab(self.tab_ExecutionDetails, "")
        self.tab_ScenarioDetails = QtWidgets.QWidget()
        self.tab_ScenarioDetails.setObjectName("tab_ScenarioDetails")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_ScenarioDetails)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textBrowser_ScenarioDetails = QtWidgets.QTextBrowser(self.tab_ScenarioDetails)
        self.textBrowser_ScenarioDetails.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_ScenarioDetails.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_ScenarioDetails.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_ScenarioDetails.setOpenExternalLinks(False)
        self.textBrowser_ScenarioDetails.setObjectName("textBrowser_ScenarioDetails")
        self.gridLayout_5.addWidget(self.textBrowser_ScenarioDetails, 0, 0, 1, 1)
        self.qTabWidget.addTab(self.tab_ScenarioDetails, "")
        self.gridLayout.addWidget(self.qTabWidget, 2, 0, 1, 1)
        SAHCMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SAHCMainWindow)
        self.qTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SAHCMainWindow)

    def retranslateUi(self, SAHCMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SAHCMainWindow.setWindowTitle(_translate("SAHCMainWindow", "Atomic Red Team Runner"))
        self.textBrowser_Info.setHtml(_translate("SAHCMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This tool makes it easy to learn and use Breach and Attack Simulation (BAS). It’s designed to simplify how you run these simulations.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To avoid problems while using the tool, it\'s best to set your Anti-Virus software to detection mode. This way, you can see what would normally be blocked, without actually stopping the tool from running.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please keep in mind:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Running certain tests (called atomic tests) can change how your system works or leave it in a less stable state. Always make sure you understand what a test does before running it.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- It’s a good idea to use a separate computer for testing—one that’s similar to your regular setup—so your main system stays safe.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- If your Anti-Virus is set to block mode (prevention mode), it might stop the tool from running or shut it down by mistake.</p></body></html>"))
        self.groupBox.setTitle(_translate("SAHCMainWindow", "Atomic Environment"))
        self.pushButton_Stop.setText(_translate("SAHCMainWindow", "Stop"))
        self.pushButton_Start.setText(_translate("SAHCMainWindow", "Run"))
        self.pushButton_Path.setText(_translate("SAHCMainWindow", "Choose Path"))
        self.label.setText(_translate("SAHCMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Atomic Path:</span></p></body></html>"))
        self.textBrowser_ExecutionStatus.setHtml(_translate("SAHCMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Progress:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.qTabWidget.setTabText(self.qTabWidget.indexOf(self.tab_ExecutionStatus), _translate("SAHCMainWindow", "Run Progress"))
        self.textBrowser_ExecutionDetails.setHtml(_translate("SAHCMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Details:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.qTabWidget.setTabText(self.qTabWidget.indexOf(self.tab_ExecutionDetails), _translate("SAHCMainWindow", "Run Details"))
        self.textBrowser_ScenarioDetails.setHtml(_translate("SAHCMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Details:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.qTabWidget.setTabText(self.qTabWidget.indexOf(self.tab_ScenarioDetails), _translate("SAHCMainWindow", "Atomic Test Details"))
